modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3"
issueTrackerURL="https://github.com/KuryKat-Modpacks/CoolStuff/issues"

[[mods]]
modId="cool_stuff"
version="0.0.1"
displayName="Cool Stuff"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="cool_logo.png"
credits="TurtyWurty for the amazing Tutorials! -> https://www.youtube.com/@TurtyWurty"
authors="KuryKat, TurtyWurty"

description='''

Just a Cool Mod created with a Tutorial

'''
